packages/dnd/src/DnD.ts
packages/dnd/src/DnDStore/index.ts
packages/dnd/src/Draggable/Base.ts
packages/dnd/src/Draggable/Draggable.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Droppable/EndDroppable.ts

Enhance verify positions 

---

packages/core-instance/src/CoreInstance.ts
packages/core-instance/src/types.ts
packages/dnd/playgrounds/dflex-react-dnd/src/DnDComponent.tsx
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/test/Store/__snapshots__/dndStore.test.ts.snap
packages/draggable/src/AbstractDraggable.ts
packages/draggable/test/__snapshots__/draggableStore.test.ts.snap
packages/store/src/Store.ts

`setViewport`
`setScrollXY`
`initELmIndicator`
`isElementHiddenInViewport`
`updateRegisteredLayoutIndicators`
`visibilityHasChanged`

Add element visibility to calculations 

---

.github/workflows/cypress.yml
packages/core-instance/src/AbstractCoreInstance.ts
packages/core-instance/src/CoreInstance.ts
packages/core-instance/src/types.ts
packages/dnd/cypress/integration/extended/visibility.transformation.spec.js
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/DnDStore/types.ts
packages/dnd/src/Draggable/Base.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Droppable/EndDroppable.ts
packages/dnd/test/Store/__snapshots__/dndStore.test.ts.snap
packages/draggable/test/__snapshots__/draggableStore.test.ts.snap
packages/store/src/Store.ts
packages/store/src/index.ts
packages/store/src/types.ts
packages/store/test/__snapshots__/store.test.ts.snap
packages/store/test/store.test.ts

Add new core API with `isInitialized`, `isPaused` and `isVisible`

---

packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/DnDStore/types.ts
packages/dnd/src/Draggable/Draggable.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Droppable/EndDroppable.ts
packages/dnd/src/Plugins/Scroll/Scroll.ts
packages/dnd/src/Plugins/Scroll/types.ts
packages/dnd/src/utils/loopInDOM.ts
packages/dnd/test/Store/__snapshots__/dndStore.test.ts.snap
packages/store/src/index.ts

Add scroll instance to each sibling list

---

packages/core-instance/src/CoreInstance.ts
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/Draggable/Draggable.ts
packages/dnd/src/Plugins/Scroll/Scroll.ts
packages/dnd/src/Plugins/Scroll/types.ts
packages/dnd/src/utils/extractOpts.ts

Fix self contained restrictions bug caused by calculating the wrong boundaries

---

package.json
packages/dnd/playgrounds/dflex-react-dnd/package.json
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/Droppable/EndDroppable.ts
packages/dnd/src/Plugins/Scroll/Scroll.ts
packages/dnd/src/Plugins/Scroll/types.ts
packages/dom-gen/src/Generator.ts
packages/dom-gen/src/types.ts
packages/dom-gen/test/delete.test.ts
packages/dom-gen/test/gen.asc.test.ts
packages/draggable/playgrounds/dflex-react-draggable/package.json
packages/store/src/Store.ts
yarn.lock

Add clear methods to `DOM-Gen`

---

packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/Plugins/Scroll/Scroll.ts

Avoid a bug where there's an overflow in CSS but the container doesn't actually have a scroll

---

packages/core-instance/src/CoreInstance.ts
packages/core-instance/src/types.ts
packages/dnd/src/DnD.ts
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/DnDStore/types.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Plugins/Scroll/Scroll.ts
packages/dnd/src/Plugins/Scroll/types.ts
packages/dnd/src/utils/loopInDOM.ts
packages/dnd/test/Store/__snapshots__/dndStore.test.ts.snap
packages/dom-gen/src/Generator.ts
packages/dom-gen/src/types.ts
packages/draggable/test/__snapshots__/draggableStore.test.ts.snap
packages/store/src/Store.ts
packages/store/src/types.ts
packages/store/test/__snapshots__/store.test.ts.snap
packages/store/test/store.test.ts

Handle invalid elements in the registry & elements accumulation to the same branch

---

packages/core-instance/src/AbstractCoreInstance.ts
packages/core-instance/src/CoreInstance.ts
packages/core-instance/src/types.ts
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/Plugins/Scroll/Scroll.ts

Add scroll dataset to the scroll container setting dynamic visibility as its value

---

packages/core-instance/src/AbstractCoreInstance.ts
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/Plugins/Scroll/Scroll.ts

Enhance cleaning up branches when elements not connected

---

packages/dnd/playgrounds/dflex-react-dnd/src/components/todo/basic/Todo.tsx
packages/dnd/src/DnD.ts
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/DnDStore/types.ts
packages/dnd/src/Draggable/Draggable.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Droppable/EndDroppable.ts
packages/dnd/src/Plugins/Scroll/Scroll.ts
packages/dnd/src/index.ts
packages/dnd/src/types.ts
packages/dnd/src/utils/extractOpts.ts
packages/dnd/test/utils/__snapshots__/extractOpts.test.ts.snap
packages/dnd/test/utils/extractOpts.test.ts

- **pending**: when DnD is not initiated but not activated yet.
- **ready**: When clicking over the registered element.
-  **dragging** and **dragEnd** as expected.
- **dragCancel** when releasing the drag without settling in the new position.
```ts
type LayoutState = "pending"
| "ready"
| "dragging"
| "dragEnd"
| "dragCancel";
```
- **Drag events**: `onDragOutContainer` | `onDragOutThreshold` - fired with `DraggedEvent`
- **Interactivity events**:  `onDragOver` | `onDragLeave`  - fired with `InteractivityEvent`
- **Sibling events**: `onLiftUpSiblings` | `onMoveDownSiblings`  - fired with `SiblingsEvent`
- **Layout events**: `onStateChange`  - fired with `LayoutStateEvent`

Introduce DnD events & layout state

---

packages/core-instance/src/CoreInstance.ts
packages/dnd/playgrounds/dflex-react-dnd/src/App.tsx
packages/dnd/playgrounds/dflex-react-dnd/src/components/essential/List.css
packages/dnd/playgrounds/dflex-react-dnd/src/components/essential/Lists.tsx
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/DnDStore/types.ts
packages/dnd/src/Droppable/DistanceCalculator.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Droppable/types.ts

Refactor comparison to the core instance and extend the mechanism to include both axes

---

packages/core-instance/src/AbstractInstance.ts
packages/core-instance/src/CoreInstance.ts
packages/core-instance/src/types.ts
packages/dnd/src/Draggable/Draggable.ts
packages/dnd/src/Draggable/index.ts
packages/dnd/src/Draggable/types.ts
packages/dnd/src/Droppable/DistanceCalculator.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Droppable/EndDroppable.ts
packages/dnd/src/Droppable/types.ts
packages/utils/src/AxesCoordinates.ts
packages/utils/src/index.ts
packages/utils/src/types.ts

Add both axes to transformers in the `Core`

---

packages/core-instance/src/AbstractInstance.ts
packages/core-instance/src/CoreInstance.ts
packages/dnd/cypress/integration/differentHeights/strict/strict.draggedSmaller.noRelease.spec.ts
packages/dnd/cypress/integration/differentHeights/strict/strict.draggedSmaller.release.spec.ts
packages/dnd/cypress/integration/extended/general/inOut.spec.ts
packages/dnd/src/Draggable/Draggable.ts
packages/dnd/src/Draggable/types.ts
packages/dnd/src/Droppable/DistanceCalculator.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Plugins/Scroll/Scroll.ts
packages/dnd/src/Plugins/Scroll/types.ts
packages/dnd/src/Plugins/Threshold/Threshold.ts
packages/dnd/src/Plugins/Threshold/index.ts
packages/dnd/src/Plugins/Threshold/types.ts
packages/dnd/src/types.ts
packages/draggable/src/AbstractDraggable.ts
packages/draggable/src/types.ts
packages/utils/src/AxesCoordinates.ts
packages/utils/src/index.ts
packages/utils/src/types.ts

```ts
interface ThresholdPointInterface {
max: number;
min: number;
}
```

Enhance `Threshold` for dragged and containers

---

packages/dnd/src/DnD.ts
packages/dnd/src/Draggable/Draggable.ts
packages/dnd/src/Draggable/DraggableAxes.ts
packages/dnd/src/Draggable/DraggableInteractive.ts
packages/dnd/src/Draggable/index.ts
packages/dnd/src/Draggable/types.ts
packages/dnd/src/Droppable/DistanceCalculator.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Droppable/EndDroppable.ts
packages/utils/src/AxesCoordinatesBool.ts
packages/utils/src/types.ts

Add a new dragging implementation for Interactive/Axes

---

packages/dnd/cypress/integration/restrictions/container-diff/horizontal.spec.ts
packages/dnd/cypress/integration/restrictions/container-diff/vertical.spec.ts
packages/dnd/src/Draggable/DraggableAxes.ts
packages/dnd/src/Draggable/types.ts
packages/dnd/src/Droppable/DistanceCalculator.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Plugins/Scroll/Scroll.ts
packages/dnd/src/Plugins/Scroll/types.ts
packages/dnd/src/types.ts
packages/utils/src/AxesCoordinates/AxesFourCoordinatesBool.ts
packages/utils/src/AxesCoordinates/index.ts
packages/utils/src/Threshold/Threshold.ts
packages/utils/src/Threshold/types.ts
packages/utils/src/index.ts
packages/utils/src/types.ts

Add threshold indicators to each active layout

---

packages/core-instance/src/CoreInstance.ts
packages/core-instance/src/types.ts
packages/dnd/cypress/integration/extended/general/inOut.spec.ts
packages/dnd/cypress/integration/restrictions/container-all/edgeCases/continuity.topELm.spec.ts
packages/dnd/cypress/integration/restrictions/self/horizontal.spec.ts
packages/dnd/cypress/integration/restrictions/self/vertical.spec.ts
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/DnDStore/types.ts
packages/dnd/src/Draggable/DraggableAxes.ts
packages/dnd/src/Droppable/DistanceCalculator.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Plugins/Scroll/Scroll.ts
packages/dnd/src/Plugins/Scroll/types.ts
packages/utils/src/AxesCoordinates/AxesFourCoordinatesBool.ts
packages/utils/src/Threshold/Threshold.ts
packages/utils/src/Threshold/types.ts
packages/utils/src/index.ts
packages/utils/src/types.ts

Fix dragged siblings boundaries calculations

---

packages/core-instance/src/AbstractInstance.ts
packages/core-instance/src/CoreInstance.ts
packages/core-instance/src/types.ts
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/Draggable/DraggableAxes.ts
packages/dnd/src/Draggable/DraggableInteractive.ts
packages/dnd/src/Draggable/types.ts
packages/dnd/src/Droppable/DistanceCalculator.ts

Update grid for `Core` and `Dragged`

---

packages/core-instance/src/CoreInstance.ts
packages/core-instance/src/types.ts
packages/dnd/src/Droppable/DistanceCalculator.ts
packages/dnd/src/Droppable/Droppable.ts

Use direction and axis with each transformation instead global instances

---

packages/core-instance/src/CoreInstance.ts
packages/core-instance/src/types.ts
packages/dnd/src/Droppable/DistanceCalculator.ts
packages/dnd/src/Droppable/EndDroppable.ts
packages/utils/src/Point/PointNum.ts
packages/utils/src/Point/index.ts
packages/utils/src/Point/types.ts
packages/utils/src/index.ts
packages/utils/src/types.ts
tsconfig.json

Store axes in translate history for each movement

---

packages/dnd/src/Draggable/DraggableAxes.ts
packages/dnd/src/Draggable/DraggableInteractive.ts
packages/dnd/src/Draggable/types.ts
packages/dnd/src/Droppable/DistanceCalculator.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Droppable/EndDroppable.ts
packages/utils/src/Migration/Migration.ts
packages/utils/src/Migration/index.ts
packages/utils/src/Migration/types.ts
packages/utils/src/index.ts

Replace placeholders with a new `Migration` class to deal with migrating from one container to another.
```ts
interface IAbstract {
index: number;
key: string;
}
interface IMigration {
/** Get the latest migrations instance */
latest(): IAbstract;
/**
* We only update indexes considering migration definition when it happens
* outside container but not moving inside it.
* So we update an index but we add a key.
*/
setIndex(index: number): void;
/** When migration from one container to another. */
add(index: number, key: string): void;
}
```

Manage containers migration

---

packages/dnd/src/Draggable/DraggableAxes.ts
packages/dnd/src/Draggable/DraggableInteractive.ts
packages/dnd/src/Draggable/types.ts
packages/dnd/src/Droppable/DistanceCalculator.ts
packages/dnd/src/Droppable/Droppable.ts
packages/dnd/src/Droppable/EndDroppable.ts
packages/utils/src/Migration/Migration.ts
packages/utils/src/Migration/types.ts

Add synthetic offset for element insertion 

---

packages/core-instance/src/Container/Container.ts
packages/core-instance/src/Container/types.ts
packages/core-instance/src/Node/CoreUtils.ts
packages/dnd/cypress/integration/multiple-containers/backAndForth/horizontally.top.spec.ts
packages/dnd/cypress/integration/multiple-containers/backAndForth/vertically.bottom.spec.ts
packages/dnd/cypress/integration/multiple-containers/differentHeights/draggedBigger.release.spec.ts
packages/dnd/src/Draggable/DraggableAxes.ts
packages/dnd/src/Droppable/DistanceCalculator.ts
packages/dnd/src/Droppable/Droppable.ts

In this case, the origin container has two elements.
1. One element transformed into another container. It has a solo element now.
2. A new element is going to be transformed into it, the container which has one element.
3. The insertion margin shouldn't cause any layout shift. 
To solve it, when the container is receiving a new element. DFlex restores the preserved last element position and calculates the margin to guarantee the given scenario where there is no shifting in positions.

Enable transformation for containers orphaned by migration

---

packages/core-instance/src/Container/Container.ts
packages/core-instance/src/Container/types.ts
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/DnDStore/types.ts
packages/dnd/src/Draggable/DraggableAxes.ts
packages/dnd/src/Draggable/types.ts
packages/dnd/src/Droppable/Droppable.ts
packages/utils/src/Threshold/Threshold.ts
packages/utils/src/Threshold/types.ts
packages/utils/src/index.ts
packages/utils/src/types.ts

So when checking where the dragged is located different heights and widths won't be a problem given when dragged is transforming all of them has the same dimensions. Still, this needs to be improved to become more dynamic since heights and widths are constantly changing or supposed to be so.

Add a unified container dimensions for each layout belongs to the same depth

---

packages/core-instance/src/Container/Container.ts
packages/core-instance/src/Container/types.ts
packages/dnd/cypress/integration/multiple-containers/continuity/multiple.intoTop.spec.ts
packages/dnd/src/DnDStore/DnDStoreImp.ts
packages/dnd/src/Draggable/DraggableAxes.ts
packages/dnd/test/dndStore.test.ts
packages/dom-gen/src/Generator.ts
packages/dom-gen/src/types.ts
packages/dom-gen/test/delete.test.ts
packages/dom-gen/test/gen.asc.test.ts

Remove `branchesOrder` as it's unused in the store

---

packages/dflex-dnd-playground/tests/multiple-containers/strict/horizontally.bottom.spec.ts
packages/dflex-dnd/src/Draggable/DraggableAxes.ts
packages/dflex-dnd/src/LayoutManager/DFlexDOMReconciler.ts
packages/dflex-dnd/src/LayoutManager/DFlexDnDStore.ts
packages/dflex-dnd/src/LayoutManager/DFlexScheduler.ts
packages/dflex-dnd/src/Mechanism/DFlexMechanismController.ts
packages/dflex-dnd/src/Mechanism/EndCycle.ts
packages/dflex-utils/src/DFlexCycle/DFlexCycle.ts

Fix observer disconnecting when reconciling the DOM

---

packages/dflex-core-instance/src/Element/DFlexCoreElement.ts
packages/dflex-dnd-playground/src/App.tsx
packages/dflex-dnd/src/LayoutManager/DFlexDOMReconciler.ts
packages/dflex-dnd/src/LayoutManager/DFlexDnDStore.ts
packages/dflex-dnd/src/LayoutManager/DFlexMutations.ts
packages/dflex-dnd/test/__snapshots__/layoutManager.test.tsx.snap
packages/dflex-draggable/src/DFlexDraggableStore.ts
packages/dflex-store/src/DFlexBaseStore.ts

- Trigger reconciliation for transformed containers.
- Non-transformed containers will update DOMRect.

Support resizing window for transformed/non-transformed containers alike

---

packages/dflex-core-instance/src/Element/DFlexCoreElement.ts
packages/dflex-dnd/src/Draggable/DraggableAxes.ts
packages/dflex-dnd/src/Mechanism/DFlexMechanismController.ts
packages/dflex-dnd/src/Mechanism/DFlexPositionUpdater.ts
packages/dflex-utils/src/Box/Box.ts
packages/dflex-utils/src/Box/BoxNum.ts
packages/dflex-utils/src/Threshold/Threshold.ts

Create stabilizing zone to prevent dragged from being stuck between two intersected thresholds.
E.g: Dragged moved into a new threshold but triggered the previous one because it's stuck inside the zone causing jarring behavior; the back-and-forth transition.

Add a stabilizer mechanism preventing dragged from being stuck inside an intersected area

---

packages/dflex-core-instance/src/Container/DFlexScrollContainer.ts
packages/dflex-dnd-playground/cypress/e2e/same-container-vertical/extended/edgeCases/differentViewport.inOut1.cy.ts
packages/dflex-dnd/src/Draggable/DraggableInteractive.ts
packages/dflex-dnd/src/LayoutManager/DFlexDnDStore.ts
packages/dflex-dnd/src/LayoutManager/DFlexVisibilityUpdater.ts
packages/dflex-dnd/src/Mechanism/DFlexScrollableElement.ts
packages/dflex-dnd/test/__snapshots__/layoutManager.test.tsx.snap
packages/dflex-utils/src/Box/Box.ts
packages/dflex-utils/src/FeatureFlags.ts
packages/dflex-utils/src/collections/computedStyleUtils.ts
packages/dflex-utils/src/collections/index.ts
packages/dflex-utils/src/dom/getParentElm.ts
packages/dflex-utils/src/eventDebounce/eventDebounce.ts
packages/dflex-utils/src/eventDebounce/index.ts
packages/dflex-utils/src/index.ts
packages/dflex-utils/test/eventDebounce.test.ts
pnpm-lock.yaml

- Removing an extra class instance.
- Decoupling event debouncing and testing it in isolation.
- Refactoring updateSiblingsVisibilityLinearly to enhance conditions.

Improve `DFlexScrollContainer` performance and testability

---

package.json
packages/dflex-dnd/src/Draggable/DraggableAxes.ts
packages/dflex-dnd/src/Draggable/DraggableInteractive.ts
packages/dflex-dnd/src/LayoutManager/DFlexDnDExportedStore.ts
packages/dflex-dnd/src/Mechanism/DFlexMechanismController.ts
packages/dflex-dnd/src/Mechanism/DFlexPositionUpdater.ts
packages/dflex-dnd/test/__snapshots__/layoutManager.test.tsx.snap
packages/dflex-store/src/DFlexBaseStore.ts
playgrounds/dflex-dnd-playground/src/App.tsx
playgrounds/dflex-next-playground/package.json
pnpm-lock.yaml
scripts/build/package.json
scripts/dflex-bundle-types/package.json
scripts/eslint-config-dflex/package.json

Exclude `$ondragleave` and `$ondragover` for list elements when dragged leaves from the top of the container

---

packages/dflex-dnd/src/Draggable/DraggableInteractive.ts
packages/dflex-dnd/src/Events/DFlexEvents.ts
packages/dflex-dnd/src/LayoutManager/DFlexDnDStore.ts
packages/dflex-dnd/src/Mechanism/EndCycle.ts
packages/dflex-utils/src/environment/updateDOMAttr.ts
playgrounds/dflex-dnd-playground/src/components/DFlexDnDComponent.tsx

This PR adds two new drag end events: `$onDragCommitted` and `$onDragTransformed`. These allow consumers to handle drag endings differently depending on whether the drag was committed to the DOM or just transformed.
Both event payloads emit the following details:
```ts
type PayloadDragMutation = {
/** Represents the main category of the drag event. */
type: typeof DRAG_CAT;
/** Indicates the timestamp when the event occurred. */
timestamp: number;
/** Targeted elements */
element: HTMLElement;
indexes: {
/** The initial index of the moved element. */
initial: number;
/** The index where it was inserted in the receiving container. */
inserted: number;
};
containers: {
/** The container from which the element originated. */
origin: HTMLElement;
/** The container where the element is now …
```

Introduce new events: `$onDragCommitted` and `$onDragTransformed`

---

packages/dflex-dnd/src/Draggable/DraggableAxes.ts
packages/dflex-dnd/test/__snapshots__/layoutManager.test.tsx.snap
packages/dflex-store/src/DFlexBaseStore.ts
packages/dflex-utils/src/environment/updateDOMAttr.ts
playgrounds/dflex-dnd-playground/src/App.tsx
playgrounds/dflex-dnd-playground/src/components/gap/bigGap.tsx
playgrounds/dflex-dnd-playground/src/components/gap/index.ts
playgrounds/dflex-dnd-playground/src/components/index.ts
playgrounds/dflex-dnd-playground/tests/features/dragSettleOnSwitch.spec.ts

Add a new flag `enableDragSettleOnSwitch ` to the global config.
```diff
/**
* Configuration options for DFlex.
*/
type DFlexGlobalConfig = {
/**
* If set to true, empty containers will be automatically removed if all of
* its elements have been successfully migrated.
*/
removeEmptyContainer: boolean;
+ /**
+  * If true, allows a dragged element to switch positions with another element
+  * and settle into the new position, even if the drag didn't end inside the
+  * new position bounds.
+  */
+ enableDragSettleOnSwitch: boolean;
/**
* If true, enables DFlex events.
*/
enableEvents: boolean;
/**
* If true, enables DFlex listeners.
*/
enableListeners: boolean;
};
```

Introduce `enableDragSettleOnSwitch` flag for enhanced drag behavior
