dflex-js/dflex

- cypress/integration/dnd/actions.spec.js
- packages/coreInstance/src/CoreInstance.js
- packages/dnd/Droppable/src/EndDroppable.js
> Fix undo approach in list updater

- packages/coreInstance/src/CoreInstance.js
- packages/dnd/src/Droppable/Droppable.js
> Trigger parent elements down from the first element (out/in)

- docs/src/css/custom.css
- docs/src/pages/index.js
Fixed dark mode text contrast problems from issue #171
> Fixes on dark mode text contrast

- docs/docs/dom-gen/intro.md
- docs/docs/drag-drop/examples.md
- docs/src/theme/ReactLiveScope/index.js
- packages/coreInstance/src/CoreInstance.js
- packages/dnd/playgrounds/dflex-react-dnd/src/lists/component-based-event/Core.jsx
- packages/dnd/playgrounds/dflex-react-dnd/src/lists/container-based-event/Core.jsx
- packages/dnd/playgrounds/dflex-react-dnd/src/todo/Todo.js
- packages/dnd/src/Draggable/Draggable.js
- packages/dnd/src/Droppable/Droppable.js
- packages/dom-gen/src/Generator.js
- packages/store/src/AbstractStore.js
- packages/store/src/Store.js
> Add ability to reset element reference without losing the pointer

- packages/dnd/cypress/integration/dnd/randomCases/outContainer.threshold.spec.js
- packages/dnd/src/Draggable/Base.ts
- packages/dnd/src/Draggable/Draggable.ts
- packages/dnd/src/Draggable/types.ts
- packages/dnd/src/Droppable/Droppable.ts
- packages/dnd/src/Droppable/EndDroppable.ts
This issue related to the maximum bottom and how it's different for one element comparing it to the container. A test will be added to avoid such an issue in the future.
> Fix outside trigger threshold  for the container 

- packages/core-instance/src/CoreInstance.ts
- packages/core-instance/src/types.ts
- packages/dnd/.gitignore
- packages/dnd/playgrounds/dflex-react-dnd/src/App.tsx
- packages/dnd/playgrounds/dflex-react-dnd/src/components/DnDComponent.tsx
- packages/dnd/src/DnDStore/DnDStoreImp.ts
- packages/dnd/src/DnDStore/types.ts
- packages/dnd/src/Draggable/Draggable.ts
- packages/dnd/src/Droppable/Droppable.ts
- packages/draggable/src/AbstractDraggable.ts
- yarn.lock
> Add `unregister` and `destroy` to the Store

- packages/dnd/src/DnDStore/DnDStoreImp.ts
- packages/dnd/src/DnDStore/types.ts
- packages/dnd/src/Draggable/Base.ts
- packages/dnd/src/Droppable/Droppable.ts
- packages/dnd/src/Droppable/EndDroppable.ts
> Add experimental aut-scroll

- packages/dnd/cypress/integration/differentHeights/inOut/inOut.draggedBigger.noRelease.spec.js
- packages/dnd/cypress/integration/differentHeights/inOut/inOut.draggedSmaller.Release.spec.js
- packages/dnd/cypress/integration/differentHeights/inOut/inOut.draggedSmaller.noRelease.spec.js
- packages/dnd/cypress/integration/differentHeights/strict/strict.draggedBigger.noRelease.spec.js
- packages/dnd/cypress/integration/differentHeights/strict/strict.draggedBigger.release.spec.js
- packages/dnd/cypress/integration/differentHeights/strict/strict.draggedSmaller.noRelease.spec.js
- packages/dnd/cypress/integration/differentHeights/strict/strict.draggedSmaller.release.spec.js
- packages/dnd/cypress/integration/essential/newPosition/collections.newPosition.spec.js
- packages/dnd/cypress/integration/essential/newPosition/continuity.noRelease.spec.js
- packages/dnd/cypress/integration/essential/newPosition/continuity.release.spec.js
- packages/dnd/cypress/integration/extended/edgeCases/differentViewport.inOut1.spec.js
- packages/dnd/cypress/integration/extended/edgeCases/differentViewport.inOut2.spec.js
- packages/dnd/cypress/integration/extended/general/inOut.spec.js
- packages/dnd/cypress/integration/extended/general/visibility.transformation.spec.js
- packages/dnd/src/Draggable/Draggable.ts
- packages/dnd/src/Droppable/Droppable.ts
- packages/dnd/src/Droppable/EndDroppable.ts
> Minimize E2E test time & remove all async undo 

- packages/dnd/cypress/integration/restrictions/self/horizontal.spec.js
- packages/dnd/cypress/integration/restrictions/self/vertical.spec.js
- packages/dnd/src/Draggable/Draggable.ts
- packages/dnd/src/utils/extractOpts.ts
- packages/dnd/test/utils/__snapshots__/extractOpts.test.ts.snap
- packages/dnd/test/utils/extractOpts.test.ts
> Fix a bug in options and self-restriction area

- packages/dnd/cypress/integration/extended/general/inOut.spec.js
- packages/dnd/src/DnDStore/DnDStoreImp.ts
- packages/dnd/src/DnDStore/types.ts
- packages/dnd/src/Draggable/Base.ts
- packages/dnd/src/Draggable/Draggable.ts
- packages/dnd/src/Draggable/types.ts
- packages/dnd/src/Droppable/Droppable.ts
- packages/dnd/src/types.ts
- packages/dnd/src/utils/extractOpts.ts
- packages/dnd/test/utils/__snapshots__/extractOpts.test.ts.snap
> Refactor `scrollElement`

- packages/dnd/playgrounds/dflex-react-dnd/src/App.tsx
- packages/dnd/playgrounds/dflex-react-dnd/src/components/index.ts
- packages/dnd/playgrounds/dflex-react-dnd/src/components/mixedRegisteredElements/UnRegisteredLists.tsx
- packages/dnd/playgrounds/dflex-react-dnd/src/components/mixedRegisteredElements/index.ts
This is for testing and debugging. Lists are intentionally unregistered, and all three lists are added to the same branch. In the future, there should be some sort of mechanism to deal with this problem/issue.
> Add lists unregistered and unsorted for further test cases

- packages/core-instance/src/CoreInstance.ts
- packages/core-instance/src/types.ts
- packages/dnd/cypress/integration/differentHeights/inOut/inOut.draggedSmaller.Release.spec.ts
- packages/dnd/src/DnDStore/DnDStoreImp.ts
- packages/dnd/src/DnDStore/types.ts
- packages/dnd/src/Draggable/Draggable.ts
- packages/dnd/src/Draggable/types.ts
- packages/dnd/src/Droppable/DistanceCalculator.ts
- packages/dnd/src/Droppable/Droppable.ts
- packages/dnd/src/Droppable/EndDroppable.ts
- packages/dnd/src/Droppable/types.ts
- packages/utils/src/AxesCoordinatesBool.ts
- packages/utils/src/index.ts
- packages/utils/src/types.ts
> Use strict `read-only` flags for Draggable

- packages/dnd/cypress/integration/restrictions/container-diff/horizontal.spec.ts
- packages/dnd/src/Draggable/DraggableAxes.ts
- packages/dnd/src/Draggable/DraggableInteractive.ts
- packages/dnd/src/Draggable/types.ts
- packages/dnd/src/Droppable/Droppable.ts
- packages/utils/src/AxesCoordinates/AxesFourCoordinatesBool.ts
> Remove `isDraggedOutPosition` and `isDraggedOutContainer`

- packages/dnd/src/Droppable/DistanceCalculator.ts
- packages/dnd/src/Droppable/Droppable.ts
Funny that this wrong flag stopped the horizontal list from working entirely.
> Remove wrong direction flag in `updateElement`

- packages/core-instance/src/CoreInstance.ts
- packages/dnd/cypress/integration/horizontal/outPosition/horizontally.outPoistion.spec.ts
- packages/dnd/playgrounds/dflex-react-dnd/src/App.tsx
- packages/dnd/playgrounds/dflex-react-dnd/src/components/essential/List.css
- packages/dnd/playgrounds/dflex-react-dnd/src/components/essential/Lists.tsx
- packages/dnd/src/DnDStore/DnDStoreImp.ts
- packages/dnd/src/DnDStore/types.ts
- packages/dnd/src/Droppable/DistanceCalculator.ts
- packages/dnd/src/Droppable/Droppable.ts
- packages/dnd/src/Droppable/EndDroppable.ts
> Reset columns for each row when calculating and positioning grid for siblings 

- packages/core-instance/src/CoreInstance.ts
- packages/core-instance/src/types.ts
- packages/dnd/src/DnDStore/DnDStoreImp.ts
- packages/dnd/src/DnDStore/types.ts
- packages/dnd/src/Droppable/Droppable.ts
- packages/dom-gen/package.json
- packages/dom-gen/src/Generator.ts
- packages/dom-gen/test/delete.test.ts
- packages/dom-gen/test/gen.asc.test.ts
- packages/dom-gen/test/gen.des.test.ts
> Add `assignBoundaries` and `getELmParentRef` to the Core

- packages/dnd/cypress/integration/multiple-containers/undo/inside.noSplit.spec.ts
- packages/dnd/cypress/integration/multiple-containers/undo/split.down.spec.ts
- packages/dnd/src/Draggable/DraggableAxes.ts
- packages/dnd/src/Draggable/DraggableInteractive.ts
- packages/dnd/src/Draggable/types.ts
- packages/dnd/src/Droppable/DistanceCalculator.ts
- packages/dnd/src/Droppable/Droppable.ts
- packages/dnd/src/Droppable/EndDroppable.ts
- packages/utils/src/Migration/Migration.ts
- packages/utils/src/Migration/types.ts
Rollback elements according to their migration history between the containers instead of checking the active container alone.
> Dealing with multiple transformations without settling into a new position

- .github/workflows/ci.yml
- packages/dnd/cypress/integration/multiple-containers/cases/extend.horizontally.spec.ts
- packages/dnd/cypress/integration/multiple-containers/essential/toOrphanList/horizontally.bottom.spec.ts
- packages/dnd/package.json
- packages/dnd/src/Draggable/DraggableAxes.ts
- packages/dnd/src/Droppable/DistanceCalculator.ts
- packages/dnd/src/Droppable/Droppable.ts
Use margin in the destination instead of synthetic margin.
> Change margin when positioning from orphan to non-orphan container

- packages/dnd/cypress/integration/multiple-containers/continuity/multiple.intoTop.spec.ts
- packages/dnd/src/DnDStore/DnDStoreImp.ts
- packages/dnd/src/Draggable/DraggableAxes.ts
- packages/dnd/test/dndStore.test.ts
> Fix continuity in extending orphan container

- packages/dnd/cypress/integration/multiple-containers/continuity/distributeIntoContainers.spec.ts
> Testing transform element to an into empty container

- packages/dnd/cypress/integration/multiple-containers/continuity/distributeIntoContainers.spec.ts
- packages/dnd/cypress/integration/multiple-containers/continuity/emptyMultiple.restore.spec.ts
- packages/dnd/cypress/integration/multiple-containers/obliquity/bottomUp/multi.spec.ts
- packages/dnd/src/DnDStore/DnDStoreImp.ts
- packages/dnd/src/Droppable/DistanceCalculator.ts
- packages/dnd/src/Droppable/Droppable.ts
- packages/utils/src/Migration/Migration.ts
- packages/utils/src/Migration/types.ts
> Fix last element preservation in the origin

- package.json
- packages/core-instance/src/Container/Container.ts
- packages/core-instance/src/Container/types.ts
- packages/dnd/cypress/integration/multiple-containers/continuity/distributeIntoContainers.spec.ts
- packages/dnd/cypress/integration/multiple-containers/continuity/emptyMultiple.restore.spec.ts
- packages/dnd/cypress/integration/multiple-containers/continuity/multiple.intoTop.spec.ts
- packages/dnd/cypress/integration/multiple-containers/obliquity/bottomUp/multi.spec.ts
- packages/dnd/cypress/integration/multiple-containers/obliquity/bottomUp/oneStep.spec.ts
- packages/dnd/cypress/integration/multiple-containers/obliquity/upBottom/multi.spec.ts
- packages/dnd/playgrounds/dflex-react-dnd/package.json
- packages/dnd/src/DnDStore/DnDStoreImp.ts
- packages/dnd/src/Draggable/DraggableAxes.ts
- packages/dnd/src/Droppable/DistanceCalculator.ts
- packages/dnd/src/Droppable/Droppable.ts
- packages/dnd/test/dndStore.test.ts
- packages/dom-gen/src/Generator.ts
- packages/dom-gen/src/types.ts
- packages/dom-gen/test/delete.test.ts
- packages/dom-gen/test/gen.asc.test.ts
- packages/draggable/playgrounds/dflex-react-draggable/package.json
- packages/utils/src/Migration/Migration.ts
- packages/utils/src/Migration/types.ts
- pnpm-lock.yaml
- scripts/eslint-config-dflex/package.json
> Add essential cases for obliquity and continuity including from/to empty container

- package.json
- packages/dflex-core-instance/src/Container/DFlexScrollContainer.ts
- packages/dflex-dnd-playground/package.json
- packages/dflex-dnd/src/Mechanism/DFlexMechanismController.ts
- packages/dflex-draggable/src/DFlexBaseDraggable.ts
- pnpm-lock.yaml
- scripts/build/package.json
- scripts/eslint-config-dflex-react/package.json
- scripts/eslint-config-dflex/package.json
This PR aims to enhance the style handling in the draggable element by refactoring and optimizing the `setMirrorStyle` and `setOrUnsetOriginStyle` functions. The changes improve reusability, reduce duplication, and make the code more concise and maintainable.
> Enhance style handling in Draggable element 

- packages/dflex-dnd/src/LayoutManager/DFlexDnDExportedStore.ts
- packages/dflex-dnd/src/LayoutManager/DFlexDnDStore.ts
- packages/dflex-dnd/src/Mutation/DFlexDirtyLeavesCollector.ts
- packages/dflex-dnd/src/Mutation/DFlexIDGarbageCollector.ts
- packages/dflex-dnd/src/Mutation/DFlexMutations.ts
- packages/dflex-dnd/src/Mutation/index.ts
- packages/dflex-dnd/test/__snapshots__/layoutManager.test.tsx.snap
- packages/dflex-dom-gen/src/DFlexDOMKeysManager.ts
- packages/dflex-store/src/DFlexBaseStore.ts
- packages/dflex-store/src/DFlexDOMManager.ts
**Changes in this Pull Request:**
1. **Refined Interface:** Removed the `isIdle` method from the Store's public interface to eliminate potential confusion with `isLayoutAvailable`.
2. **Enhanced Asynchronous Control:** Implemented a robust mechanism for pending methods to effectively manage asynchronous functionalities during register and unregister operations.
3. **Internal Garbage Collection Flag:** Introduced a new flag to accurately detect ongoing internal garbage collection processes, providing better control over resource management.
4. **Optimized Registration Process:** Implemented a check to prevent the store from unnecessarily proceeding with registration when the element is already present in the registry, improving operational efficiency.
5. **Preemptive Connectivity Check:** …
> Refine Garbage Collection and Registration Workflow

- package.json
- packages/dflex-core-instance/package.json
- packages/dflex-dnd/package.json
- packages/dflex-dom-gen/package.json
- packages/dflex-draggable/package.json
- packages/dflex-next-playground/next.config.js
- packages/dflex-next-playground/tsconfig.build.json
- packages/dflex-store/package.json
- packages/dflex-utils/package.json
Related: https://github.com/microsoft/TypeScript/issues/52363
> Update `package.json` exports to include type definitions
